# Generated by Django 2.2.12 on 2023-04-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230427_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('CUP', 'Cup'), ('OZS', 'Ounce'), ('TBS', 'Tablespoon'), ('TSP', 'Teaspoon'), ('BOX', 'Box'), ('GRM', 'Gram'), ('LRG', 'Large'), ('MED', 'Medium'), ('SML', 'Small'), ('LBS', 'LBS')], max_length=3),
        ),
    ]
