# Generated by Django 4.0.10 on 2023-07-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20230608_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('CUP', 'Cup'), ('OZS', 'Ounce'), ('TBS', 'Tablespoon'), ('TSP', 'Teaspoon'), ('BOX', 'Box'), ('GRM', 'Gram'), ('LRG', 'Large'), ('MED', 'Medium'), ('SML', 'Small'), ('LBS', 'LBS'), ('CNS', 'Cannoli Shell')], max_length=3),
        ),
    ]
